# Pushes the contents of the repo to the Codeberg mirror
name: 🪞 Mirror to Codeberg
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 0'

permissions:
  contents: read

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: lissy93/repo-mirror-action@abc23f7156083e8101cfbfe34a33159d3ce2e1d2 # v1.6.0
        with:
          ssh_key: ${{ secrets.CODEBERG_SSH }}
          host: git@codeberg.org
          user: alicia
          repo: personal-security-checklist
